export const PERMISSIONS = [
  "admin.access",
  "pages.read",
  "pages.create",
  "pages.update",
  "pages.delete",
  "pages.publish",
  "pages.preview",
  "media.read",
  "media.create",
  "media.update",
  "media.delete",
  "header.read",
  "header.update",
  "footer.read",
  "footer.update",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "users.assignRole",
  "themes.read",
  "themes.create",
  "themes.update",
  "themes.delete",
  "siteSettings.read",
  "siteSettings.update",
  "auditLogs.read",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
