/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Controla o acesso editorial no CMS. Apenas administradores podem alterar perfis.
   */
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Cadastre imagens e documentos usados nos blocos, SEO e identidade visual. O texto alternativo e obrigatorio para acessibilidade.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Classifique o papel editorial da midia. SVG nao e aceito; para icones e logos, use PNG ou WebP aprovados.
   */
  usage: 'content' | 'background' | 'logo' | 'icon' | 'infographic' | 'document';
  /**
   * Descreva objetivamente a imagem para pessoas que usam leitores de tela.
   */
  alt: string;
  /**
   * Opcional. Use quando a imagem precisar de credito, contexto ou complemento editorial.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Crie e organize paginas editoriais do portal. Use rascunho, preview e publicacao para controlar o ciclo editorial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nome exibido no CMS e usado como referencia principal da pagina.
   */
  title: string;
  /**
   * Use "home" para a pagina inicial. Para paginas internas, use letras minusculas, numeros e hifens. O valor "/" tambem vira "home".
   */
  slug: string;
  /**
   * Use Ativo para conteudo publicavel. Use Inativo para remover a pagina da navegacao e do acesso publico sem apagar historico.
   */
  lifecycleStatus: 'active' | 'inactive';
  /**
   * Monte a pagina escolhendo blocos prontos, agrupados por Conteúdo, Mídia e Ações. As aparências usam opções controladas pelo Design System; nenhum bloco executa contador ou timer automático nesta fase.
   */
  layout?:
    | (
        | HeroBlock
        | RichTextBlock
        | ImageTextBlock
        | CardsBlock
        | CTABlock
        | IconGridBlock
        | FAQAccordionBlock
        | AlertBoxBlock
        | ActionBannersBlock
        | FullWidthImageBannerBlock
      )[]
    | null;
  /**
   * Configure titulo, resumo, OpenGraph, robots e URL canonica para buscadores quando forem diferentes do conteudo principal.
   */
  seo?: {
    /**
     * Opcional. Se vazio, o titulo principal da pagina ou o SEO padrao continua sendo usado.
     */
    metaTitle?: string | null;
    /**
     * Resumo curto usado por buscadores e cards de compartilhamento.
     */
    metaDescription?: string | null;
    /**
     * Opcional. Use uma imagem institucional representativa para redes sociais e OpenGraph.
     */
    socialImage?: (number | null) | Media;
    /**
     * Opcional. Informe apenas quando a pagina publica tiver uma URL canonica absoluta e confirmada.
     */
    canonical?: string | null;
    /**
     * Quando marcado, orienta buscadores a nao indexar esta pagina.
     */
    noIndex?: boolean | null;
    /**
     * Quando marcado, orienta buscadores a nao seguir links desta pagina.
     */
    noFollow?: boolean | null;
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Texto curto acima do titulo, usado para contextualizar a pagina.
   */
  eyebrow?: string | null;
  /**
   * Mensagem principal da pagina. Pode ser longo, mas prefira uma frase clara.
   */
  title: string;
  /**
   * Texto opcional abaixo do titulo para orientar o usuario antes da acao.
   */
  description?: string | null;
  /**
   * Usada apenas no modelo Imagem lateral. Em telas pequenas, a imagem fica empilhada abaixo do texto.
   */
  image?: (number | null) | Media;
  /**
   * Link opcional exibido como botao principal da abertura.
   */
  cta?: {
    /**
     * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
     */
    label?: string | null;
    /**
     * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
     */
    type?: ('internal' | 'external') | null;
    /**
     * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
     */
    page?: (number | null) | Page;
    /**
     * Informe o endereco completo, incluindo http:// ou https://.
     */
    url?: string | null;
    /**
     * Recomendado para links externos, mantendo o portal aberto na aba atual.
     */
    newTab?: boolean | null;
  };
  /**
   * Opcional. Use midia cadastrada para compor o fundo do destaque sem alterar o arquivo original.
   */
  background?: {
    /**
     * Imagem principal do fundo. Se ausente, o destaque usa o visual padrao.
     */
    image?: (number | null) | Media;
    /**
     * Opcional. Use quando a composicao desktop nao funcionar bem em telas estreitas.
     */
    mobileImage?: (number | null) | Media;
    overlay?: ('none' | 'light' | 'dark') | null;
    focalPoint?: ('center' | 'top' | 'bottom' | 'left' | 'right') | null;
  };
  /**
   * Padrao alinha o conteudo a esquerda; Centralizado destaca uma mensagem curta; Imagem lateral exibe texto e imagem lado a lado no desktop. Este bloco nao possui contador nem timer automatico.
   */
  variant: 'default' | 'centered' | 'split';
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Area para texto, listas, links e subtitulos. A aparencia final segue a tipografia editorial do portal.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Padrao usa largura ampla para conteudos variados. Leitura estreita favorece textos corridos longos.
   */
  variant: 'default' | 'narrow';
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  /**
   * Titulo da secao que acompanha a imagem.
   */
  title: string;
  /**
   * Texto complementar exibido ao lado da imagem em telas maiores.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Imagem principal do bloco. Em celulares, ela aparece antes do texto.
   */
  image: number | Media;
  /**
   * Escolha o lado da imagem em telas grandes. Em dispositivos moveis, imagem e texto ficam empilhados.
   */
  variant: 'image-left' | 'image-right';
  /**
   * Link opcional exibido apos o texto.
   */
  cta?: {
    /**
     * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
     */
    label?: string | null;
    /**
     * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
     */
    type?: ('internal' | 'external') | null;
    /**
     * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
     */
    page?: (number | null) | Page;
    /**
     * Informe o endereco completo, incluindo http:// ou https://.
     */
    url?: string | null;
    /**
     * Recomendado para links externos, mantendo o portal aberto na aba atual.
     */
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  /**
   * Titulo opcional exibido antes dos cards.
   */
  title?: string | null;
  /**
   * Texto opcional para explicar o conjunto de cards.
   */
  description?: string | null;
  /**
   * Padrao cobre listas editoriais gerais; modalidades destaca opcoes de regularizacao sem criar outro tipo de bloco.
   */
  variant: 'default' | 'modalities';
  /**
   * Adicione de 1 a 12 cards. O layout ajusta a quantidade de colunas conforme a largura da tela.
   */
  items: {
    mediaSource?: ('none' | 'icon' | 'image') | null;
    mediaPosition?: ('top' | 'left' | 'right') | null;
    imageSize?: ('small' | 'medium' | 'large') | null;
    imageAspect?: ('original' | 'square' | '4:3' | '16:9') | null;
    fit?: ('cover' | 'contain') | null;
    /**
     * Texto principal do card. Pode quebrar linha sem afetar os demais itens.
     */
    title: string;
    /**
     * Resumo ou orientacao exibida dentro do card.
     */
    description: string;
    /**
     * Opcional para conteudo antigo; obrigatorio quando Tipo de midia for Icone.
     */
    icon?: (number | null) | Media;
    /**
     * Imagem do card. O arquivo original permanece preservado na biblioteca de midia.
     */
    image?: (number | null) | Media;
    /**
     * Opcional. Use quando o card deve encaminhar para outra pagina ou servico.
     */
    link?: {
      /**
       * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
       */
      label?: string | null;
      /**
       * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
       */
      type?: ('internal' | 'external') | null;
      /**
       * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
       */
      page?: (number | null) | Page;
      /**
       * Informe o endereco completo, incluindo http:// ou https://.
       */
      url?: string | null;
      /**
       * Recomendado para links externos, mantendo o portal aberto na aba atual.
       */
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  /**
   * Mensagem curta que encerra uma secao ou orienta o proximo passo.
   */
  title: string;
  /**
   * Texto opcional para explicar o contexto da chamada.
   */
  description?: string | null;
  /**
   * Destino obrigatorio da chamada. Use pagina interna ou URL oficial externa.
   */
  action: {
    /**
     * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
     */
    label: string;
    /**
     * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
     */
    type: 'internal' | 'external';
    /**
     * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
     */
    page?: (number | null) | Page;
    /**
     * Informe o endereco completo, incluindo http:// ou https://.
     */
    url?: string | null;
    /**
     * Recomendado para links externos, mantendo o portal aberto na aba atual.
     */
    newTab?: boolean | null;
  };
  /**
   * Padrao serve para chamadas gerais; Destaque institucional usa fundo forte; Compacta funciona melhor em encerramentos repetidos.
   */
  variant: 'default' | 'brand' | 'compact';
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconGridBlock".
 */
export interface IconGridBlock {
  /**
   * Titulo curto que contextualiza o conjunto de itens com icones.
   */
  title: string;
  /**
   * Texto opcional para orientar a leitura antes da grade.
   */
  description?: string | null;
  /**
   * Padrao destaca descricoes; compacto favorece listas mais densas.
   */
  variant: 'default' | 'compact';
  /**
   * Adicione itens curtos com icone. Reordene conforme a prioridade editorial.
   */
  items: {
    /**
     * Opcional. Use imagens simples e com texto alternativo adequado.
     */
    icon?: (number | null) | Media;
    /**
     * Texto curto exibido junto ao icone. Evite paragrafos longos.
     */
    description: string;
    /**
     * Opcional. Use apenas quando o item encaminhar para detalhe ou servico.
     */
    link?: {
      /**
       * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
       */
      label?: string | null;
      /**
       * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
       */
      type?: ('internal' | 'external') | null;
      /**
       * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
       */
      page?: (number | null) | Page;
      /**
       * Informe o endereco completo, incluindo http:// ou https://.
       */
      url?: string | null;
      /**
       * Recomendado para links externos, mantendo o portal aberto na aba atual.
       */
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock".
 */
export interface FAQAccordionBlock {
  /**
   * Titulo exibido antes da lista de perguntas.
   */
  title: string;
  /**
   * Texto opcional para contextualizar as perguntas.
   */
  description?: string | null;
  /**
   * Padrao usa mais espacamento; compacto favorece paginas densas.
   */
  variant: 'default' | 'compact';
  /**
   * Cada item vira uma linha expansivel acessivel por teclado.
   */
  items: {
    /**
     * Pergunta clara e direta exibida no acordeao.
     */
    question: string;
    /**
     * Resposta editorial. Use links somente para canais oficiais ou paginas do portal.
     */
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AlertBoxBlock".
 */
export interface AlertBoxBlock {
  /**
   * Opcional. Use quando o aviso precisar de uma chamada curta.
   */
  title?: string | null;
  /**
   * Texto do aviso. Mantenha linguagem orientativa e evite conclusoes definitivas.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Define apenas o tom visual do aviso dentro do Design System.
   */
  type: 'info' | 'warning';
  /**
   * Opcional. Use para encaminhar o usuario a uma pagina ou servico oficial.
   */
  link?: {
    /**
     * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
     */
    label?: string | null;
    /**
     * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
     */
    type?: ('internal' | 'external') | null;
    /**
     * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
     */
    page?: (number | null) | Page;
    /**
     * Informe o endereco completo, incluindo http:// ou https://.
     */
    url?: string | null;
    /**
     * Recomendado para links externos, mantendo o portal aberto na aba atual.
     */
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'alertBox';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionBannersBlock".
 */
export interface ActionBannersBlock {
  /**
   * Opcional. Use quando o conjunto de faixas precisar de contexto.
   */
  title?: string | null;
  /**
   * Grade mostra faixas lado a lado; empilhado favorece chamadas longas.
   */
  variant: 'grid' | 'stacked';
  /**
   * Cada faixa deve ter uma acao clara e um tom escolhido do Design System.
   */
  banners: {
    /**
     * Mensagem curta da faixa de acao.
     */
    title: string;
    /**
     * Opcional. Use para explicar a acao antes do botao.
     */
    description?: string | null;
    /**
     * Mapeia a faixa para tokens do Design System, sem cores livres.
     */
    appearance: 'primary' | 'brand' | 'accent';
    button: {
      /**
       * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
       */
      label: string;
      /**
       * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
       */
      type: 'internal' | 'external';
      /**
       * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
       */
      page?: (number | null) | Page;
      /**
       * Informe o endereco completo, incluindo http:// ou https://.
       */
      url?: string | null;
      /**
       * Recomendado para links externos, mantendo o portal aberto na aba atual.
       */
      newTab?: boolean | null;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'actionBanners';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBannerBlock".
 */
export interface FullWidthImageBannerBlock {
  /**
   * Imagem principal do banner. O layout controla largura, altura e responsividade.
   */
  desktopImage: number | Media;
  /**
   * Opcional. Use uma composicao alternativa quando a imagem desktop nao for adequada em telas estreitas.
   */
  mobileImage?: (number | null) | Media;
  /**
   * Opcional. Use apenas quando a mensagem tambem deve existir como texto acessivel sobre a imagem.
   */
  content?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    actions?:
      | {
          /**
           * Texto visivel para o usuario. Use uma acao clara, como Abrir pagina ou Saiba mais.
           */
          label: string;
          /**
           * Escolha pagina interna para navegar no portal ou URL externa para encaminhar a servico oficial.
           */
          type: 'internal' | 'external';
          /**
           * Pagina publicada ou em rascunho dentro deste CMS. Mudancas de slug nao quebram este relacionamento.
           */
          page?: (number | null) | Page;
          /**
           * Informe o endereco completo, incluindo http:// ou https://.
           */
          url?: string | null;
          /**
           * Recomendado para links externos, mantendo o portal aberto na aba atual.
           */
          newTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  contentPosition: 'left' | 'center' | 'right';
  overlay: 'none' | 'light' | 'dark';
  imageFit: 'cover' | 'contain';
  focalPoint: 'center' | 'top' | 'bottom' | 'left' | 'right';
  variant: 'default' | 'compact' | 'immersive';
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullWidthImageBanner';
}
/**
 * Consulte eventos editoriais registrados automaticamente. Logs nao devem ser editados ou criados manualmente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  timestamp: string;
  actor?: (number | null) | User;
  actorEmail?: string | null;
  action: 'create' | 'update' | 'publish' | 'unpublish' | 'deactivate' | 'reactivate';
  collection: string;
  documentId: string;
  documentTitle: string;
  version?: string | null;
  changedFields?:
    | {
        field: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  usage?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lifecycleStatus?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        iconGrid?: T | IconGridBlockSelect<T>;
        faqAccordion?: T | FAQAccordionBlockSelect<T>;
        alertBox?: T | AlertBoxBlockSelect<T>;
        actionBanners?: T | ActionBannersBlockSelect<T>;
        fullWidthImageBanner?: T | FullWidthImageBannerBlockSelect<T>;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        canonical?: T;
        noIndex?: T;
        noFollow?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  description?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  background?:
    | T
    | {
        image?: T;
        mobileImage?: T;
        overlay?: T;
        focalPoint?: T;
      };
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  image?: T;
  variant?: T;
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  variant?: T;
  items?:
    | T
    | {
        mediaSource?: T;
        mediaPosition?: T;
        imageSize?: T;
        imageAspect?: T;
        fit?: T;
        title?: T;
        description?: T;
        icon?: T;
        image?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  action?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconGridBlock_select".
 */
export interface IconGridBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  variant?: T;
  items?:
    | T
    | {
        icon?: T;
        description?: T;
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock_select".
 */
export interface FAQAccordionBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  variant?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AlertBoxBlock_select".
 */
export interface AlertBoxBlockSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  type?: T;
  link?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActionBannersBlock_select".
 */
export interface ActionBannersBlockSelect<T extends boolean = true> {
  title?: T;
  variant?: T;
  banners?:
    | T
    | {
        title?: T;
        description?: T;
        appearance?: T;
        button?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBannerBlock_select".
 */
export interface FullWidthImageBannerBlockSelect<T extends boolean = true> {
  desktopImage?: T;
  mobileImage?: T;
  content?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        actions?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
      };
  contentPosition?: T;
  overlay?: T;
  imageFit?: T;
  focalPoint?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  timestamp?: T;
  actor?: T;
  actorEmail?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  documentTitle?: T;
  version?: T;
  changedFields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure a navegacao principal exibida no topo do portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Opcional. Se vazio, o nome do site continua identificando o portal.
   */
  logo?: (number | null) | Media;
  /**
   * Lista de paginas principais exibidas no cabecalho. Mantenha poucos itens para facilitar a leitura.
   */
  navigation?:
    | {
        /**
         * Texto curto exibido no cabecalho.
         */
        label: string;
        /**
         * Pagina de destino dentro do portal. Mudancas de slug nao quebram este relacionamento.
         */
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure informacoes institucionais e links exibidos no rodape do portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Opcional. Informe somente se houver canal oficial vigente para atendimento.
   */
  phone?: string | null;
  /**
   * Opcional. Informe somente endereco institucional monitorado.
   */
  email?: string | null;
  /**
   * Opcional. Informe endereco institucional vigente somente quando confirmado pelos canais oficiais.
   */
  address?: string | null;
  /**
   * Texto livre para orientar sobre atendimento presencial ou informar que deve ser consultado nos canais oficiais.
   */
  inPersonService?: string | null;
  /**
   * Perfis oficiais exibidos no rodape. Mantenha somente canais institucionais ativos.
   */
  socialLinks?:
    | {
        /**
         * Nome curto exibido para identificar o canal oficial, como Instagram ou YouTube.
         */
        label: string;
        /**
         * Endereco completo do perfil oficial, incluindo https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Links para servicos e paginas oficiais relacionados ao portal.
   */
  institutionalLinks?:
    | {
        /**
         * Texto curto exibido no rodape.
         */
        label: string;
        /**
         * Endereco completo do servico ou pagina oficial, incluindo https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure informacoes gerais, links oficiais, SEO padrao e cores institucionais controladas pelo Design System.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Nome institucional usado como identificacao principal do portal.
   */
  siteName: string;
  /**
   * Data institucional exibida pelo conteudo editorial quando aplicavel. Mantenha este valor alinhado aos atos oficiais.
   */
  deadline: string;
  /**
   * Canais oficiais usados pelo portal para encaminhar o usuario. Evite links informais ou temporarios.
   */
  officialLinks?:
    | {
        /**
         * Texto curto e claro para identificar o canal oficial.
         */
        label: string;
        /**
         * Endereco completo do canal oficial, incluindo https://.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ajuste apenas as cores permitidas pelo Design System. Nao e possivel inserir CSS livre.
   */
  branding?: {
    /**
     * Cor principal de botoes, links e destaques. Use hexadecimal curto ou longo, como #007a73.
     */
    primaryColor?: string | null;
    /**
     * Cor de fundos fortes, como areas de destaque. Use hexadecimal curto ou longo.
     */
    secondaryColor?: string | null;
    /**
     * Cor suave para superficies de apoio e chamadas secundarias. Use hexadecimal curto ou longo.
     */
    accentColor?: string | null;
  };
  /**
   * Valores usados quando uma pagina nao possui SEO proprio configurado.
   */
  defaultSEO?: {
    /**
     * Opcional. Se vazio, o titulo principal da pagina ou o SEO padrao continua sendo usado.
     */
    metaTitle?: string | null;
    /**
     * Resumo curto usado por buscadores e cards de compartilhamento.
     */
    metaDescription?: string | null;
    /**
     * Opcional. Use uma imagem institucional representativa para redes sociais e OpenGraph.
     */
    socialImage?: (number | null) | Media;
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  inPersonService?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  institutionalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  deadline?: T;
  officialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  branding?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
      };
  defaultSEO?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        socialImage?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}